[package]
name = "probly-search"
version = "0.1.0"
authors = ["marcus-pousette <marcus.pousette@quantleaf.com>"]
edition = "2018"
licence = "MIT"
homepage = "https://github.com/quantleaf/probly-search"
repository = "https://github.com/quantleaf/probly-search"
documentation = "https://github.com/quantleaf/probly-search"
readme = "README.md"
keywords = ["search", "quert", "bm25","index"]
categories = ["text-processing"]
