[package]
name = "probly-search"
version = "0.1.0"
authors = ["marcus-pousette <marcus.pousette@quantleaf.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
